"""adding test table

Revision ID: 650096371d3b
Revises: 05e2c0670e34
Create Date: 2023-04-08 10:43:43.328376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650096371d3b'
down_revision = '05e2c0670e34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
